### ISSUE TITLE
Deluxe Vouchers problem

### ISSUE THREAD

**Issue by Dinoosawruss** [CoderMarido/DeluxeVouchers#5]
I am going to start by saying you will not see me on your purchasers list it was the server owner that purchased the plugin and here is our licence DV591482

When I run /deluxevouchers editor I get this error
https://www.spigotmc.org/resources/%E2%9C%A6-deluxevouchers-%E2%9C%A6-editor-gui-mysql-extremely-customizable-1-voucher-resource-1-8-1-13.52480/

**Comment by CoderMarido** [comment]
This issue has been resolved in the latest version of DeluxeVouchers, thanks for reporting.
